apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-back-deployment
spec:
  selector:
   matchLabels:
    app: spring-app-back
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-app-back
    spec:
      containers:
        - name: spring-app-back
          image: devops-apirest:0.0.3       
          ports:
            - containerPort: 7080
              name: springappbport